### PR TITLE
removed laminas/laminas-log dependency

### PR DESCRIPTION
**Pull request by Jurj-Bogdan**
#9 
Removed laminas/laminas-log dependency. Package requires additional checks. 
Do not merge this pull request

### CODE REVIEW

**Comment by alexmerlin** [comment]
@arhimede @MarioRadu @Jurj-Bogdan 
Is this PR still relevant?

**Comment by arhimede** [comment]
?

**Comment by alexmerlin** [comment]
This is related to #9, where @MarioRadu left a [comment](https://github.com/dotkernel/dot-form/issues/9#issuecomment-1294929495) saying that more investigation is needed.
I'm not sure, though, if any developments have happened on that matter in the meantime.

**Comment by marioradu05** [comment]
This issue was fixed in https://github.com/dotkernel/dot-form/pull/15.

**Pull request closed without merging**
